[package]
name = "bastroblasto"
version = "0.1.0"
authors = ["Lucas Clemente Vella <lvella@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic", "vorbis"] }
rand = "0.8"

[profile.release]
lto = true
